/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "MainApplication.h"

#include "MainWindow.h"

MainApplication::MainApplication()
{
}
    
const String MainApplication::getApplicationName()
{
    return ProjectInfo::projectName;
}

const String MainApplication::getApplicationVersion()
{
    return ProjectInfo::versionString;
}

bool MainApplication::moreThanOneInstanceAllowed()
{
    return true;
}

void MainApplication::initialise (const String& command_line)
{
    mainWindow = new MainWindow (getApplicationName());
}

void MainApplication::shutdown()
{
}

void MainApplication::suspended()
{
}

void MainApplication::resumed()
{
}

void MainApplication::backButtonPressed()
{
    quit();
}

void MainApplication::systemRequestedQuit()
{
    // This is called when the app is being asked to quit: you can ignore this
    // request and let the app carry on running, or call quit() to allow the app to close.
    quit();

}

void MainApplication::anotherInstanceStarted (const String& commandLine)
{
    // When another instance of the app is launched while this one is running,
    // this method is invoked, and the commandLine parameter tells you what
    // the other instance's command-line arguments were.
    ignoreUnused (commandLine);
}
